// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace, KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";
import type { TwoFactorAgent } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    AGENT: __TelnyxActorNamespace<TwoFactorAgent>;
    TELNYX: __TelnyxClient;
    KV: __TelnyxKvNamespace;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    AGENT: __TelnyxActorNamespace<TwoFactorAgent>;
    TELNYX: __TelnyxClient;
    KV: __TelnyxKvNamespace;
  }
}

export {};
