// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { CustomerAgent } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    CUSTOMERS: __TelnyxActorNamespace<CustomerAgent>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_PUBLIC_KEY"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    CUSTOMERS: __TelnyxActorNamespace<CustomerAgent>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_PUBLIC_KEY"): Promise<string> };
  }
}

export {};
