// Generated by `telnyx-edge types`. DO NOT EDIT.
// (Hand-checked-in for the example repo; re-run `telnyx-edge types` after
// changing actor bindings in telnyx.toml.)

import type {
  ActorNamespace as __TelnyxActorNamespace,
  CloudStorageBucket as __TelnyxCloudStorageBucket,
} from "@telnyx/edge-runtime";
import type { default as __TelnyxClient } from "telnyx";
import type { CorpusAgent } from "./src/corpus-agent.js";
import type { PersonaAgent } from "./src/persona-agent.js";

declare global {
  interface Env {
    CORPUS: __TelnyxActorNamespace<CorpusAgent>;
    PERSONAS: __TelnyxActorNamespace<PersonaAgent>;
    TELNYX: __TelnyxClient;
    KNOWLEDGE: __TelnyxCloudStorageBucket;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    CORPUS: __TelnyxActorNamespace<CorpusAgent>;
    PERSONAS: __TelnyxActorNamespace<PersonaAgent>;
    TELNYX: __TelnyxClient;
    KNOWLEDGE: __TelnyxCloudStorageBucket;
  }
}

export {};
