// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { InboxAgent } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    INBOX: __TelnyxActorNamespace<InboxAgent>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_API_KEY" | "TELNYX_PUBLIC_KEY" | "AGENTMAIL_API_KEY" | "AGENTMAIL_INBOX" | "AGENTMAIL_WEBHOOK_SECRET"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    INBOX: __TelnyxActorNamespace<InboxAgent>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_API_KEY" | "TELNYX_PUBLIC_KEY" | "AGENTMAIL_API_KEY" | "AGENTMAIL_INBOX" | "AGENTMAIL_WEBHOOK_SECRET"): Promise<string> };
  }
}

export {};
