// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { StreamingAgent } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    AGENTS: __TelnyxActorNamespace<StreamingAgent>;
    TELNYX: __TelnyxClient;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    AGENTS: __TelnyxActorNamespace<StreamingAgent>;
    TELNYX: __TelnyxClient;
  }
}

export {};
