"""Pure Markdown renderers for bot-created pull request descriptions."""

from __future__ import annotations

GATE_MARKER = "<!-- PRE_PR_GATE_STATUS -->"


def render_code_sample_body(*, issue_id: str, issue_url: str, ticket_title: str,
                            sample_name: str, summary: str) -> str:
    return f"""## Summary

{summary}

## Source / Tracking

| Field | Value |
|---|---|
| Linear issue | [{issue_id}]({issue_url}) |
| Ticket title | {ticket_title} |
| Sample path | `{sample_name}/` |
| Created by | `telnyx-devrel-bot[bot]` |

## Changes

- Added the generated `{sample_name}` sample.
- Registered the sample in repository indexes and mappings.
- Updated generated repository documentation where required.

## Validation

{GATE_MARKER}

## Review Checklist

- [ ] Verify the generated implementation against the Linear specification.
- [ ] Run the sample locally and confirm the documented flow.
- [ ] Confirm required files, mappings, and links are correct.
- [ ] Confirm no credentials, personal data, or unsafe example values are present.

## Merge Readiness

This PR was generated by an LLM using the linked ticket specification. Human review is required before merge.
"""


def render_syndication_body(*, sample_name: str, assignee: str,
                            source_url: str, generated_files: list[str]) -> str:
    files = "\n".join(f"- `{name}`" for name in sorted(generated_files))
    return f"""## Summary

Adds auto-generated AEO syndication content for `{sample_name}`.

## Source / Tracking

| Field | Value |
|---|---|
| Code sample | {source_url} |
| Owner | {assignee} |
| Created by | `telnyx-devrel-bot[bot]` via ACP Hermes |
| Tracker update | Pending human review |

## Changes

{files}

## Validation

- Generated content from the merged code-sample README and source.
- Publication links, technical claims, and sensitive values require human verification.

## Review Checklist

- [ ] Verify every technical claim against the code sample.
- [ ] Check links, commands, placeholder phone numbers, and credentials.
- [ ] Add/update the owner's tracker entry and Linear sub-issue table.
- [ ] Confirm channel-specific drafts are ready before publication.

## Merge Readiness

Keep this PR open while publication URLs and tracker statuses are completed. Human approval is required before merge.
"""


def inject_gate_status(body: str, failures: list[str]) -> str:
    if failures:
        status = (
            "> ⚠️ Pre-PR gates needing reviewer attention:\n"
            + "\n".join(f"- ❌ {failure}" for failure in failures)
        )
    else:
        status = "> ✅ All pre-PR gates passed locally before this PR was opened."
    if GATE_MARKER in body:
        return body.replace(GATE_MARKER, status, 1)
    return body + "\n\n---\n\n" + status
