/**
 * Shared types for the agent-message-replay sample.
 *
 * A "recording" is a captured agent conversation: an ordered list of steps,
 * each with a role, the message text, the gap to the previous step (pacing),
 * and the agent state the original agent had reached when it emitted the
 * step. Replay re-enacts both halves — messages stream through the
 * MessageLog, and state changes broadcast as live state patches.
 */

/**
 * The Edge function environment, as generated by `telnyx-edge types` —
 * see `telnyx-env.d.ts` at the sample root for the declared bindings.
 */
export type ReplayEnv = Env;

/** One recorded step of a conversation replay. */
export interface ScriptStep {
  /** Who emitted the message. Mirrors the MessageLog roles. */
  role: "user" | "assistant" | "system";
  /** The message text. */
  content: string;
  /** Milliseconds to wait AFTER the previous step before playing this one. */
  delayMs: number;
  /** The original agent's stage after this step (state-change visualization). */
  stage?: string;
}

/** A stored conversation recording, keyed by conversation id. */
export interface ConversationRecording {
  conversationId: string;
  steps: ScriptStep[];
}

/**
 * Durable replay state. Kept flat and merge-patch friendly: every field is
 * a scalar, so every `setState` call broadcasts as a small RFC 7396 patch.
 */
export interface ReplayState extends Record<string, unknown> {
  /** Replay lifecycle: empty → ready → playing ⇄ paused → finished. */
  status: "empty" | "ready" | "playing" | "paused" | "finished";
  /** Index of the NEXT script step to play (0-based; `total` when done). */
  playhead: number;
  /** Number of steps in the loaded recording. */
  total: number;
  /** Playback speed multiplier (0.5, 1, 2, 4). */
  speed: number;
  /** Whether LLM commentary is emitted after each assistant step. */
  commentary: boolean;
  /** True while a commentary completion is in flight. */
  commentaryBusy: boolean;
  /** The re-enacted original-agent stage (state-change visualization). */
  agentStage: string;
  /** Which recording is loaded. */
  conversationId: string;
}

/** Valid playback speeds, exposed so the UI and tests share one list. */
export const SPEEDS = [0.5, 1, 2, 4] as const;

export function isSpeed(value: unknown): value is (typeof SPEEDS)[number] {
  return SPEEDS.includes(value as (typeof SPEEDS)[number]);
}

/** Clamp a playhead index into [0, total]. */
export function clampPlayhead(index: number, total: number): number {
  if (!Number.isFinite(index)) return 0;
  return Math.min(Math.max(Math.trunc(index), 0), total);
}

/** A single commentary annotation, as carried by the event stream. */
export interface CommentaryPayload {
  /** Index of the script step the commentary is about. */
  stepIndex: number;
  /** The LLM-generated annotation text. */
  text: string;
  /** Model that produced the commentary. */
  model: string;
}
