// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { AssistRelay, CoachRoom, CoachRegistry } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    RELAY: __TelnyxActorNamespace<AssistRelay>;
    COACHROOMS: __TelnyxActorNamespace<CoachRoom>;
    REGISTRY: __TelnyxActorNamespace<CoachRegistry>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_API_KEY" | "CALL_CONTROL_CONNECTION_ID" | "TELNYX_NUMBER" | "SUPERVISOR_DEVICE" | "COACH_AUTH"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    RELAY: __TelnyxActorNamespace<AssistRelay>;
    COACHROOMS: __TelnyxActorNamespace<CoachRoom>;
    REGISTRY: __TelnyxActorNamespace<CoachRegistry>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_API_KEY" | "CALL_CONTROL_CONNECTION_ID" | "TELNYX_NUMBER" | "SUPERVISOR_DEVICE" | "COACH_AUTH"): Promise<string> };
  }
}

export {};
