// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    TELNYX: __TelnyxClient;
    EVENTS: __TelnyxKvNamespace;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    TELNYX: __TelnyxClient;
    EVENTS: __TelnyxKvNamespace;
  }
}

export {};
