// Generated by `telnyx-edge types`. DO NOT EDIT.
// (Hand-checked-in for the example repo; re-run `telnyx-edge types` after
// changing actor bindings in telnyx.toml.)

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { default as __TelnyxClient } from "telnyx";
import type { DocActor } from "./src/doc-actor.js";

declare global {
  interface Env {
    DOCS: __TelnyxActorNamespace<DocActor>;
    TELNYX: __TelnyxClient;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    DOCS: __TelnyxActorNamespace<DocActor>;
    TELNYX: __TelnyxClient;
  }
}

export {};
