// Code generated by `telnyx-edge types`. DO NOT EDIT.
// (Checked in so the sample typechecks without a live function — regenerate
// with `npm run types` after `telnyx-edge new-func` assigns your func_id.)

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { ReplayAgent } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    REPLAY: __TelnyxActorNamespace<ReplayAgent>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_API_KEY"): Promise<string> };
    MODEL?: string;
    DEMO_MODE?: string;
    REPLAY_TOKEN?: string;
    INGEST_TOKEN?: string;
    DEMO_FROM_NUMBER?: string;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    REPLAY: __TelnyxActorNamespace<ReplayAgent>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_API_KEY"): Promise<string> };
    MODEL?: string;
    DEMO_MODE?: string;
    REPLAY_TOKEN?: string;
    INGEST_TOKEN?: string;
    DEMO_FROM_NUMBER?: string;
  }
}

export {};
