export function demoHtml(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Network Incident Agent · Telnyx Edge</title>
<style>
:root{--ink:#101014;--paper:#f5f3eb;--card:#fff;--line:#dcd8ca;--green:#00e3aa;--blue:#3434ef;--orange:#ff7043;--red:#d73535;--muted:#6b6a63;--soft:#e9fbf6;--shadow:0 18px 48px rgba(16,16,20,.08)}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;min-height:100vh}button,input,textarea{font:inherit}.topbar{height:68px;padding:0 4vw;background:var(--ink);color:#fff;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:11px;font-size:21px;font-weight:850;letter-spacing:-.04em}.brandmark{width:25px;height:25px;background:var(--green);clip-path:polygon(50% 0,100% 38%,82% 100%,18% 100%,0 38%)}.runtime{font:12px ui-monospace,monospace;color:#bbb}.runtime i{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 11px var(--green);margin-right:8px}
main{max-width:1450px;margin:auto;padding:30px 4vw 50px}.hero{display:flex;align-items:flex-end;justify-content:space-between;gap:28px;margin-bottom:24px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.14em;font-weight:850;color:var(--blue);margin-bottom:8px}.hero h1{font-size:clamp(34px,4.5vw,62px);line-height:.98;letter-spacing:-.06em;margin:0;max-width:840px}.hero h1 em{font-style:normal;color:var(--blue)}.subtitle{max-width:720px;color:var(--muted);line-height:1.5;margin:14px 0 0}.controls{display:flex;gap:10px;align-items:center}.run{border:0;border-radius:12px;background:var(--green);color:var(--ink);font-weight:850;padding:15px 21px;cursor:pointer;box-shadow:0 8px 24px rgba(0,227,170,.22);white-space:nowrap}.run:hover{transform:translateY(-2px)}.run:disabled{opacity:.55;transform:none;cursor:wait}.mode{display:flex;align-items:center;gap:8px;border:1px solid var(--line);background:#fff;border-radius:11px;padding:12px;font-size:12px;font-weight:700}.mode input{accent-color:var(--blue)}
nav{display:flex;gap:8px;margin-bottom:16px}.tab{border:1px solid var(--line);background:#fff;border-radius:20px;padding:8px 13px;color:var(--muted);font-size:12px;font-weight:750}.tab.active{background:var(--ink);color:#fff;border-color:var(--ink)}.shell{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(350px,.65fr);gap:19px}.panel{background:var(--card);border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow);overflow:hidden}.panelhead{display:flex;align-items:center;justify-content:space-between;padding:16px 19px;border-bottom:1px solid var(--line)}.panelhead h2{font-size:14px;margin:0}.badge{font:800 10px ui-monospace,monospace;padding:5px 9px;border-radius:20px;background:#eee;color:var(--muted)}
.incident{padding:20px}.overview{display:grid;grid-template-columns:1.25fr repeat(3,.55fr);gap:12px}.summary,.metric{border:1px solid var(--line);border-radius:14px;padding:16px}.summary{background:linear-gradient(130deg,#111 0,#25252d 100%);color:#fff;min-height:130px}.summarytop{display:flex;justify-content:space-between;gap:10px}.incidentid{font:700 11px ui-monospace,monospace;color:#aaa}.severity{padding:5px 8px;border-radius:7px;background:var(--red);font:850 11px ui-monospace,monospace}.summary h3{font-size:19px;margin:18px 0 5px}.summary p{color:#bbb;font-size:12px;line-height:1.45;margin:0}.metric label{display:block;text-transform:uppercase;letter-spacing:.1em;color:var(--muted);font-size:9px;font-weight:850}.metric strong{display:block;font-size:31px;letter-spacing:-.05em;margin:13px 0 4px}.metric span{font-size:11px;color:var(--muted)}
.journey{padding:24px 4px 10px}.steps{display:grid;grid-template-columns:repeat(5,1fr);position:relative;gap:9px}.steps:before{content:"";height:2px;background:var(--line);position:absolute;left:7%;right:7%;top:19px}.step{position:relative;text-align:center}.dot{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;margin:auto;background:#eee;border:4px solid #fff;box-shadow:0 0 0 1px var(--line);font-size:12px;font-weight:900;position:relative;z-index:1}.step.done .dot{background:var(--green);box-shadow:0 0 0 1px var(--green)}.step.active .dot{background:var(--blue);color:#fff;box-shadow:0 0 0 7px rgba(52,52,239,.1);animation:pulse 1.2s infinite}@keyframes pulse{50%{box-shadow:0 0 0 11px rgba(52,52,239,.05)}}.step b{display:block;text-transform:capitalize;font-size:11px;margin-top:9px}.step small{color:var(--muted);font-size:9px}.lower{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid var(--line);min-height:300px}.block{padding:18px}.block:first-child{border-right:1px solid var(--line)}.sectiontitle{text-transform:uppercase;letter-spacing:.11em;color:var(--muted);font-size:9px;font-weight:850;margin-bottom:12px}.customer{display:flex;align-items:center;justify-content:space-between;padding:10px;border:1px solid var(--line);border-radius:9px;margin-bottom:8px;font:12px ui-monospace,monospace}.customer span:last-child{color:#008d6b;font:800 9px system-ui}.callbox{border-radius:12px;background:var(--soft);padding:14px;font-size:12px;line-height:1.5;color:#08664f;min-height:103px}.callbox:before{content:"VOICE RESPONSE";display:block;font-size:9px;letter-spacing:.1em;font-weight:850;margin-bottom:7px}.rca{background:var(--ink);color:#ccc;border-radius:12px;padding:14px;height:135px;overflow:auto;white-space:pre-wrap;font:10px/1.5 ui-monospace,monospace;margin-top:12px}
.side{display:flex;flex-direction:column}.feed{padding:8px 18px 18px;overflow:auto;height:590px}.event{display:grid;grid-template-columns:29px 1fr;gap:10px;padding:11px 0;border-bottom:1px solid #ece9df}.eventdot{width:27px;height:27px;border-radius:8px;display:grid;place-items:center;background:var(--soft);color:#007d5e;font-size:10px;font-weight:900}.event strong{font-size:11px}.event p{font-size:11px;color:var(--muted);line-height:1.4;margin:3px 0}.event time{font:9px ui-monospace,monospace;color:#aaa}.notice{margin:0 18px 18px;padding:12px;border-radius:10px;background:var(--soft);color:#07664f;font-size:11px;line-height:1.45}.notice.error{background:#fff0ed;color:#9d2817}
.setup{display:none;padding:18px;margin-bottom:16px}.setup.open{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field label{display:block;font-size:10px;font-weight:800;color:var(--muted);margin-bottom:5px}.field input,.field textarea{width:100%;border:1px solid var(--line);border-radius:9px;padding:10px;background:#fff}.field.wide{grid-column:1/-1}.field textarea{resize:vertical;min-height:65px}.configButton{border:0;background:transparent;color:var(--blue);font-size:12px;font-weight:800;cursor:pointer}
@media(max-width:1050px){.hero{align-items:flex-start;flex-direction:column}.shell{grid-template-columns:1fr}.feed{height:340px}}@media(max-width:750px){.overview{grid-template-columns:1fr 1fr}.summary{grid-column:1/-1}.lower{grid-template-columns:1fr}.block:first-child{border-right:0;border-bottom:1px solid var(--line)}.controls{width:100%;flex-wrap:wrap}.run{flex:1}.setup.open{grid-template-columns:1fr}.field.wide{grid-column:auto}}
</style></head><body>
<header class="topbar"><div class="brand"><span class="brandmark"></span>telnyx</div><div class="runtime"><i></i>EDGE · AGENT SDK · LIVE</div></header>
<main><section class="hero"><div><div class="eyebrow">Durable incident orchestration</div><h1>The actor <em>is the outage.</em></h1><p class="subtitle">One durable agent owns the complete incident—from detection and proactive customer SMS to voice context, recovery, CloudFS RCA, and recurrence checks.</p></div><div class="controls"><label class="mode"><input id="liveMode" type="checkbox"> Send real Telnyx SMS</label><button class="run" id="runButton">Run incident demo →</button></div></section>
<nav><button class="tab active">Incident command</button><button class="configButton" id="configButton">Configure demo parameters</button></nav>
<section class="panel setup" id="setup"><div class="field"><label>Incident ID</label><input id="incidentId" value="INC-EDGE-042"></div><div class="field"><label>Affected services (comma separated)</label><input id="services" value="Voice, Messaging"></div><div class="field wide"><label>Incident description</label><textarea id="description">Elevated packet loss is affecting voice and messaging traffic in the Amsterdam edge region.</textarea></div><div class="field wide"><label>Affected customer numbers (E.164, comma separated)</label><input id="customers" value="+15555550101,+15555550102,+15555550103"><small>Demo mode masks numbers and simulates delivery. Live mode sends real SMS to these numbers.</small></div></section>
<div class="shell"><section class="panel"><div class="panelhead"><h2>Incident command center</h2><span class="badge" id="statusBadge">READY</span></div><div class="incident"><div class="overview"><div class="summary"><div class="summarytop"><span class="incidentid" id="incidentLabel">NO ACTIVE INCIDENT</span><span class="severity" id="severity">—</span></div><h3 id="title">Awaiting detection</h3><p id="descriptionText">Configure the scenario or run the prepared recording flow.</p></div><div class="metric"><label>Status</label><strong id="statusMetric">—</strong><span>durable actor state</span></div><div class="metric"><label>Customers</label><strong id="customerMetric">0</strong><span>stored in KV</span></div><div class="metric"><label>SMS sent</label><strong id="smsMetric">0</strong><span id="smsMode">simulation</span></div></div>
<div class="journey"><div class="steps" id="steps"></div></div></div><div class="lower"><div class="block"><div class="sectiontitle">Affected customers · KV namespace</div><div id="customersList"><div class="customer"><span>No customers loaded</span><span>WAITING</span></div></div><div class="sectiontitle" style="margin-top:18px">Inbound customer call</div><div class="callbox" id="callPreview">Incident-aware voice context will appear once the actor is initialized.</div></div><div class="block"><div class="sectiontitle">CloudFS root-cause artifact</div><div id="rcaPath" style="font:11px ui-monospace,monospace;color:var(--muted)">No RCA written</div><pre class="rca" id="rca">Run the flow to generate a durable RCA document.</pre></div></div></section>
<aside class="panel side"><div class="panelhead"><h2>Live incident timeline</h2><span class="badge">EMBEDDED SQL</span></div><div class="feed" id="feed"><div style="padding:40px 10px;text-align:center;color:#999;font-size:12px">Timeline events will stream here.</div></div><div class="notice" id="notice">Demo mode is safe: Telnyx sends are simulated until you explicitly enable live SMS.</div></aside></div></main>
<script>
const stages=['detected','investigating','restoring','resolved','closed'];const el=id=>document.getElementById(id);let currentId='';let running=false;let timer=null;
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function stageIndex(status){return Math.max(0,stages.indexOf(status));}function renderSteps(status){const idx=stageIndex(status);el('steps').innerHTML=stages.map((s,i)=>'<div class="step '+(i<idx?'done':i===idx?'active':'')+'"><div class="dot">'+(i<idx?'✓':i+1)+'</div><b>'+s+'</b><small>'+(['alert fired','ops engaged','traffic recovering','RCA generated','recurrence clean'][i])+'</small></div>').join('');}
function render(data){const s=data.state||data;const timeline=data.timeline||[];const customers=data.customers||[];el('incidentLabel').textContent=s.incidentId||'NO ACTIVE INCIDENT';el('severity').textContent=s.severity||'—';el('title').textContent=s.title||'Awaiting detection';el('descriptionText').textContent=s.description||'No description';el('statusMetric').textContent=(s.status||'—').toUpperCase();el('customerMetric').textContent=s.affectedCustomerCount||0;el('smsMetric').textContent=s.notificationsSent||0;el('smsMode').textContent=s.liveMode?'real Telnyx delivery':'safe simulation';renderSteps(s.status||'detected');el('statusBadge').textContent=(s.status||'ready').toUpperCase();el('statusBadge').style.background=s.status==='resolved'||s.status==='closed'?'#ccf9ee':s.status?'#dcdcff':'#eee';
el('customersList').innerHTML=customers.length?customers.map(c=>'<div class="customer"><span>'+escapeHtml(c)+'</span><span>'+((s.notificationsSent||0)>0?'NOTIFIED':'AFFECTED')+'</span></div>').join(''):'<div class="customer"><span>No customer numbers configured</span><span>DEMO</span></div>';
el('feed').innerHTML=timeline.length?timeline.map(e=>'<div class="event"><div class="eventdot">'+escapeHtml(e.type.split('.').map(x=>x[0]).join('').slice(0,2).toUpperCase())+'</div><div><strong>'+escapeHtml(e.type)+'</strong><p>'+escapeHtml(e.message)+'</p><time>'+new Date(e.createdAt).toLocaleTimeString()+'</time></div></div>').join(''):'<div style="padding:40px 10px;text-align:center;color:#999;font-size:12px">Timeline events will stream here.</div>';
if(s.rcaPath)el('rcaPath').textContent=s.rcaPath;}
async function refresh(){if(!currentId)return;try{const r=await fetch('/api/incident?incidentId='+encodeURIComponent(currentId));const data=await r.json();if(r.ok){render(data);const c=await fetch('/api/call-preview?incidentId='+encodeURIComponent(currentId));const context=await c.json();if(c.ok)el('callPreview').textContent='“'+context.message+'”';}}catch{}}
function values(){return{incidentId:el('incidentId').value.trim(),title:'Amsterdam edge packet loss',description:el('description').value.trim(),affectedServices:el('services').value.split(',').map(x=>x.trim()).filter(Boolean),affectedCustomers:el('customers').value.split(',').map(x=>x.trim()).filter(Boolean),liveMode:el('liveMode').checked,paceMs:1050};}
async function start(){if(running)return;running=true;const body=values();currentId=body.incidentId;el('runButton').disabled=true;el('runButton').textContent='Incident in progress…';el('notice').className='notice';el('notice').textContent=body.liveMode?'LIVE MODE: sending real SMS through your configured Telnyx number.':'Safe demo mode: showing the real workflow without sending SMS.';el('rca').textContent='RCA will be generated after resolution…';timer=setInterval(refresh,260);
try{const r=await fetch('/api/demo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Demo failed');render(data.snapshot);el('rcaPath').textContent=data.rca.path;el('rca').textContent=data.rca.content;el('notice').textContent='Incident resolved. RCA persisted to CloudFS and a durable recurrence check is scheduled.';}
catch(e){el('notice').className='notice error';el('notice').textContent=e.message;el('statusBadge').textContent='ERROR';}finally{clearInterval(timer);await refresh();running=false;el('runButton').disabled=false;el('runButton').textContent='Run another incident →';}}
el('runButton').addEventListener('click',start);el('configButton').addEventListener('click',()=>el('setup').classList.toggle('open'));renderSteps('detected');
</script></body></html>`;
}
