// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { CustomerAgent } from "./src/index";
import type { default as __TelnyxClient } from "telnyx";

declare global {
  interface Env {
    AGENT: __TelnyxActorNamespace<CustomerAgent>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_API_KEY" | "TELNYX_AI_ASSISTANT_ID" | "TELNYX_FROM_NUMBER" | "USE_MOCK_SALESFORCE"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    AGENT: __TelnyxActorNamespace<CustomerAgent>;
    TELNYX: __TelnyxClient;
    SECRETS: { get(binding: "TELNYX_API_KEY" | "TELNYX_AI_ASSISTANT_ID" | "TELNYX_FROM_NUMBER" | "USE_MOCK_SALESFORCE"): Promise<string> };
  }
}

export {};
